name: Builder

on: push

jobs:
  builder:
    name: build README.md
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade PyGithub jinja2

      - name: Build the file
        run: python3 ./src/pageBuilder.py

      - name: Push created file
        run: |
          git config --global user.name "${{ GITHUB_ACTOR }}"
          git config --global user.email "${{ GITHUB_ACTOR }}@users.noreply.github.com"
          git add --all
          git commit -m "Updates README.md"
          git push
