name: README Builder

on:
  push:
    branches:
      - main
  schedule:
    # run every Monday at 05:00 UTC
    - cron: '0 5 * * 1'

jobs:
  builder:
    name: Build the README.md file
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade PyGithub jinja2

      - name: Build the file
        run: python3 ./src/pageBuilder.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Commit if needed
        id: commit-result
        run: |
          if ! git diff --quiet --exit-code; then
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add --all
            git commit -m "Automatic update by GitHub Actions workflow"
            echo "push_needed=true" >> "$GITHUB_ENV"
          else
            echo "push_needed=false" >> "$GITHUB_ENV"
          fi

      - name: Push changes
        if: ${{ env.push_needed == 'true' }}
        run: |
          git push
